#!/bin/sh

usage()
{
	echo "*******************************************"
	echo "USAGE"
	echo "./make [object]"
	echo "DESCIPTION"
	echo "object:  config/menuconfig/install/clean"
	echo "*******************************************"
}

str_to_lower()
{
	echo $1 | tr '[A-Z]' '[a-z]'
}

str=$(str_to_lower $1)
if [ "$str" == "config" ]; then
	cp default.config .config
elif [ "$str" == "menuconfig" ]; then
	make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- menuconfig
elif [ "$str" == "install" ]; then
	make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j8
	make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- install
elif [ "$str" == "clean" ]; then
	make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- distclean
else
	usage
	exit 1
fi

